### ISSUE TITLE
Clicking discovered spots when enough flags are already set, should reveal the rest of the spots

### ISSUE THREAD

**Issue by JPPieczocha** [NehuenCuenca/buscaminas-vue#1]
I noticed there is a feature missing, when clicking an already discovered spot when the flag was already set all adjacent squares should be discovered. I'll leave a couple of screenshots demonstrating my point.

Let's say we have the game like the following:
![image](https://github.com/NehuenCuenca/buscaminas-vue/assets/70308282/12587f5e-f679-46d1-ab8c-83601caa0934)
If the player clicks the spot with the number 2 between those two flags, all three blocks above are instantly revealed like this:
![image](https://github.com/NehuenCuenca/buscaminas-vue/assets/70308282/8adbf7a3-aa12-4551-97e2-88ee69b57f0f)

And if a player misplaces a flag, all spots are revealed including the bomb and it is an instant game over:
![image](https://github.com/NehuenCuenca/buscaminas-vue/assets/70308282/607c7f99-c885-497f-9c7e-c866ad37e1dd)
![image](https://github.com/NehuenCuenca/buscaminas-vue/assets/70308282/703d5320-0650-4318-b502-03c9a37cdb35)

Currently when clicking an already discovered spot, nothing happens.

**Comment by NehuenCuenca** [comment]
Ohh you right!!, i didn't remember that, well, now im gonna throw the code to trash. Nah just kidding, gonna investigate what can i do 🤓, thx jhon paul @JPPieczocha 
![590-5900765_ironicmeme-ironic-png-sunglasses-emoji-smileyface-emoji-with](https://github.com/NehuenCuenca/buscaminas-vue/assets/63419744/54c17ce8-c6f0-4c70-8ffa-41de892f30f6)
